/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: ea23cba8ecf918b2fb318b96015bb7e4)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	AI_GATEWAY_API_KEY: string;
	ChatAgent: DurableObjectNamespace<import("./src/server/index").ChatAgent>;
	ThreadIndex: DurableObjectNamespace<import("./src/server/index").ThreadIndex>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "ChatAgent" | "ThreadIndex";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_API_KEY">> {}
}
