/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: ad6c8f4634907679dfab0abc80d6fa2e)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	AI_GATEWAY_API_KEY: string;
	DEMO_RATE_LIMIT: string;
	ChatAgent: DurableObjectNamespace<import("./src/server/index").ChatAgent>;
	ThreadIndex: DurableObjectNamespace<import("./src/server/index").ThreadIndex>;
	RATE_LIMITER: DurableObjectNamespace<import("./src/server/index").RateLimiter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "ChatAgent" | "ThreadIndex" | "RateLimiter";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_API_KEY" | "DEMO_RATE_LIMIT">> {}
}
